# Generated by Django 5.2.4 on 2025-07-10 17:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('imagen', models.CharField(blank=True, max_length=500, null=True)),
                ('video', models.CharField(blank=True, max_length=500, null=True)),
                ('link_entradas', models.CharField(blank=True, max_length=500, null=True)),
                ('precio_anticipado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_taquilla', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ubicacion', models.CharField(max_length=255)),
                ('categoria', models.CharField(choices=[('concierto', 'Concierto'), ('clubbing', 'Clubbing'), ('cancelado', 'Cancelado')], max_length=20)),
                ('sala', models.CharField(choices=[('Sala 1', 'Sala 1'), ('Sala 2', 'Sala 2')], max_length=10)),
                ('instagram', models.CharField(blank=True, max_length=255, null=True)),
                ('youtube', models.CharField(blank=True, max_length=255, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
