# Generated by Django 5.2.4 on 2025-07-10 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_rename_events_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-fecha_inicio'], 'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
        migrations.AddField(
            model_name='event',
            name='actualizado_por',
            field=models.ForeignKey(help_text='Usuario que actualizó el evento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_actualizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='creado_por',
            field=models.ForeignKey(help_text='Usuario que creó el evento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL amigable para el evento', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='categoria',
            field=models.CharField(choices=[('concierto', 'Concierto'), ('clubbing', 'Clubbing'), ('cancelado', 'Cancelado')], help_text='Categoría del evento', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='descripcion',
            field=models.TextField(help_text='Descripción detallada del evento'),
        ),
        migrations.AlterField(
            model_name='event',
            name='fecha_fin',
            field=models.DateTimeField(help_text='Fecha y hora de fin del evento'),
        ),
        migrations.AlterField(
            model_name='event',
            name='fecha_inicio',
            field=models.DateTimeField(help_text='Fecha y hora de inicio del evento'),
        ),
        migrations.AlterField(
            model_name='event',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Imagen principal del evento', null=True, upload_to='eventos/imagenes/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='link_entradas',
            field=models.URLField(blank=True, help_text='Enlace para comprar entradas', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='nombre',
            field=models.CharField(help_text='Nombre único del evento', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='precio_anticipado',
            field=models.DecimalField(decimal_places=2, help_text='Precio de la entrada con anticipación', max_digits=10),
        ),
        migrations.AlterField(
            model_name='event',
            name='precio_taquilla',
            field=models.DecimalField(decimal_places=2, help_text='Precio de la entrada en taquilla', max_digits=10),
        ),
        migrations.AlterField(
            model_name='event',
            name='sala',
            field=models.CharField(choices=[('Sala 1', 'Sala 1'), ('Sala 2', 'Sala 2')], help_text='Sala donde se realiza el evento', max_length=10),
        ),
        migrations.AlterField(
            model_name='event',
            name='ubicacion',
            field=models.CharField(help_text='Ubicación del evento', max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='video',
            field=models.URLField(blank=True, help_text='URL del video promocional', max_length=500, null=True),
        ),
    ]
