# Generated by Django 5.2.4 on 2025-07-10 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_options_event_actualizado_por_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='nombre',
            field=models.CharField(help_text='Nombre del evento', max_length=255),
        ),
    ]
