# Generated by Django 5.2.4 on 2025-07-10 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='precio_anticipado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio de la entrada con anticipación', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='precio_taquilla',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio de la entrada en taquilla', max_digits=10, null=True),
        ),
    ]
