# Generated by Django 4.2 on 2025-10-30 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_precio_anticipado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='fecha_fin',
            field=models.DateTimeField(help_text='Formato dd/mm/aaaa hh:mm'),
        ),
        migrations.AlterField(
            model_name='event',
            name='fecha_inicio',
            field=models.DateTimeField(help_text='Formato dd/mm/aaaa hh:mm'),
        ),
        migrations.AlterField(
            model_name='event',
            name='precio_anticipado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio de la entrada anticipada', max_digits=10, null=True),
        ),
    ]
